[package]
name = "lotka_volterra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
ndarray-rand = "0.13.0"
ndarray-parallel = "0.3.0"
rayon = "1.5.1"
image = "0.23.14"
